// <auto-generated />
using System;
using ERPServer.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERPServer.Migrations.SystemInfo
{
    [DbContext(typeof(SystemInfoContext))]
    partial class SystemInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERPServer.Models.SystemInfo.SystemLicenseInfo", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorizedQuantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("Environment")
                        .IsRequired()
                        .HasColumnType("varbinary(MAX)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<DateTime>("ProductExpireTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ProductLicenseStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<byte[]>("Sign")
                        .IsRequired()
                        .HasColumnType("varbinary(MAX)");

                    b.HasKey("ProductID");

                    b.ToTable("SystemLicenseInfos");
                });

            modelBuilder.Entity("ERPServer.Models.SystemInfo.SystemModuleInfo", b =>
                {
                    b.Property<int>("ModuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LicenseInfoProductID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModuleExpireTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModuleLicenseStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("ModuleID");

                    b.HasIndex("LicenseInfoProductID");

                    b.ToTable("SystemModuleInfo");
                });

            modelBuilder.Entity("ERPServer.Models.SystemInfo.SystemSetInfo", b =>
                {
                    b.Property<string>("CorporationCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CorporationAddress")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<byte[]>("CorporationLogo")
                        .HasColumnType("image");

                    b.Property<string>("CorporationName")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<string>("WebAddress")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.HasKey("CorporationCode");

                    b.ToTable("SystemInfo");

                    b.HasData(
                        new
                        {
                            CorporationCode = "kdixgioakfgehgi"
                        });
                });

            modelBuilder.Entity("ERPServer.Models.SystemInfo.SystemModuleInfo", b =>
                {
                    b.HasOne("ERPServer.Models.SystemInfo.SystemLicenseInfo", "LicenseInfo")
                        .WithMany("ModuleLicenseInfo")
                        .HasForeignKey("LicenseInfoProductID");
                });
#pragma warning restore 612, 618
        }
    }
}
