// <auto-generated />
using System;
using ERPServer.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERPServer.Migrations.SystemInfo
{
    [DbContext(typeof(SystemInfoContext))]
    partial class SystemInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERPServer.Models.SystemInfo.SystemSetInfo", b =>
                {
                    b.Property<string>("CorporationCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CorporationAddress")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<byte[]>("CorporationLogo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CorporationName")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<string>("WebAddress")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.HasKey("CorporationCode");

                    b.ToTable("SystemInfo");

                    b.HasData(
                        new
                        {
                            CorporationCode = "kdixgioakfgehgi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
