// <auto-generated />
using System;
using ERPServer.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERPServer.Migrations
{
    [DbContext(typeof(PrivilegeManagementContext))]
    [Migration("20191118061545_AddPrivilegeUser")]
    partial class AddPrivilegeUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERPServer.Models.PrivilegeManagement.Department", b =>
                {
                    b.Property<decimal>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<decimal>("ParentDepartmentID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("UserID")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("DepartmentID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Department");
                });

            modelBuilder.Entity("ERPServer.Models.PrivilegeManagement.OperationLog", b =>
                {
                    b.Property<decimal>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<decimal>("UserID")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("LogID");

                    b.HasIndex("UserID");

                    b.ToTable("OperationLog");
                });

            modelBuilder.Entity("ERPServer.Models.PrivilegeManagement.Right", b =>
                {
                    b.Property<decimal>("RightID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<decimal>("ParentRightID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("RightName")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.HasKey("RightID");

                    b.ToTable("Right");
                });

            modelBuilder.Entity("ERPServer.Models.PrivilegeManagement.Role", b =>
                {
                    b.Property<decimal>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<decimal>("ParentRoleID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.HasKey("RoleID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("ERPServer.Models.PrivilegeManagement.RoleRightRelation", b =>
                {
                    b.Property<decimal>("RelationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("RightID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("RoleID")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("RelationID");

                    b.HasIndex("RightID");

                    b.HasIndex("RoleID");

                    b.ToTable("RoleRightRelation");
                });

            modelBuilder.Entity("ERPServer.Models.PrivilegeManagement.User", b =>
                {
                    b.Property<decimal>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CurrentLoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LoginCount")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<string>("MobileNum")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1m,
                            CreateTime = new DateTime(2019, 11, 18, 14, 15, 44, 967, DateTimeKind.Local).AddTicks(8513),
                            CurrentLoginTime = new DateTime(2019, 11, 18, 14, 15, 44, 968, DateTimeKind.Local).AddTicks(4999),
                            Email = "",
                            LastLoginTime = new DateTime(2019, 11, 18, 14, 15, 44, 968, DateTimeKind.Local).AddTicks(4714),
                            LoginCount = 0m,
                            LoginName = "SuperAdmin",
                            MobileNum = "13584584928",
                            Password = "202CB962AC59075B964B07152D234B70",
                            UserName = "丁瑞琦"
                        });
                });

            modelBuilder.Entity("ERPServer.Models.PrivilegeManagement.UserRoleRelation", b =>
                {
                    b.Property<decimal>("RelationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("RoleID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("UserID")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("RelationID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRoleRelation");
                });

            modelBuilder.Entity("ERPServer.Models.PrivilegeManagement.Department", b =>
                {
                    b.HasOne("ERPServer.Models.PrivilegeManagement.User", "User")
                        .WithOne("Department")
                        .HasForeignKey("ERPServer.Models.PrivilegeManagement.Department", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERPServer.Models.PrivilegeManagement.OperationLog", b =>
                {
                    b.HasOne("ERPServer.Models.PrivilegeManagement.User", "Operater")
                        .WithMany("OperationLog")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERPServer.Models.PrivilegeManagement.RoleRightRelation", b =>
                {
                    b.HasOne("ERPServer.Models.PrivilegeManagement.Right", "Right")
                        .WithMany("RoleRightRelation")
                        .HasForeignKey("RightID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPServer.Models.PrivilegeManagement.Role", "Role")
                        .WithMany("RoleRightRelation")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERPServer.Models.PrivilegeManagement.UserRoleRelation", b =>
                {
                    b.HasOne("ERPServer.Models.PrivilegeManagement.Role", "Role")
                        .WithMany("UserRoleRelation")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPServer.Models.PrivilegeManagement.User", "User")
                        .WithMany("UserRoleRelation")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
